// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetHealthAliveHandlerFunc turns a function with the right signature into a get health alive handler
type GetHealthAliveHandlerFunc func(GetHealthAliveParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetHealthAliveHandlerFunc) Handle(params GetHealthAliveParams) middleware.Responder {
	return fn(params)
}

// GetHealthAliveHandler interface for that can handle valid get health alive params
type GetHealthAliveHandler interface {
	Handle(GetHealthAliveParams) middleware.Responder
}

// NewGetHealthAlive creates a new http.Handler for the get health alive operation
func NewGetHealthAlive(ctx *middleware.Context, handler GetHealthAliveHandler) *GetHealthAlive {
	return &GetHealthAlive{Context: ctx, Handler: handler}
}

/*GetHealthAlive swagger:route GET /health/alive health getHealthAlive

Health check of xApp Manager - Liveness probe

*/
type GetHealthAlive struct {
	Context *middleware.Context
	Handler GetHealthAliveHandler
}

func (o *GetHealthAlive) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetHealthAliveParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
