// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetHealthReadyHandlerFunc turns a function with the right signature into a get health ready handler
type GetHealthReadyHandlerFunc func(GetHealthReadyParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetHealthReadyHandlerFunc) Handle(params GetHealthReadyParams) middleware.Responder {
	return fn(params)
}

// GetHealthReadyHandler interface for that can handle valid get health ready params
type GetHealthReadyHandler interface {
	Handle(GetHealthReadyParams) middleware.Responder
}

// NewGetHealthReady creates a new http.Handler for the get health ready operation
func NewGetHealthReady(ctx *middleware.Context, handler GetHealthReadyHandler) *GetHealthReady {
	return &GetHealthReady{Context: ctx, Handler: handler}
}

/*GetHealthReady swagger:route GET /health/ready health getHealthReady

Readiness check of xApp Manager - Readiness probe

*/
type GetHealthReady struct {
	Context *middleware.Context
	Handler GetHealthReadyHandler
}

func (o *GetHealthReady) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetHealthReadyParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
