// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetHealthReadyOKCode is the HTTP code returned for type GetHealthReadyOK
const GetHealthReadyOKCode int = 200

/*GetHealthReadyOK xApp Manager is ready for service

swagger:response getHealthReadyOK
*/
type GetHealthReadyOK struct {
}

// NewGetHealthReadyOK creates GetHealthReadyOK with default headers values
func NewGetHealthReadyOK() *GetHealthReadyOK {

	return &GetHealthReadyOK{}
}

// WriteResponse to the client
func (o *GetHealthReadyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// GetHealthReadyServiceUnavailableCode is the HTTP code returned for type GetHealthReadyServiceUnavailable
const GetHealthReadyServiceUnavailableCode int = 503

/*GetHealthReadyServiceUnavailable xApp Manager is not ready for service

swagger:response getHealthReadyServiceUnavailable
*/
type GetHealthReadyServiceUnavailable struct {
}

// NewGetHealthReadyServiceUnavailable creates GetHealthReadyServiceUnavailable with default headers values
func NewGetHealthReadyServiceUnavailable() *GetHealthReadyServiceUnavailable {

	return &GetHealthReadyServiceUnavailable{}
}

// WriteResponse to the client
func (o *GetHealthReadyServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(503)
}
