// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi RIC appmgr
This is a draft API for RIC appmgr


    Schemes:
      http
    Host: hostname
    BasePath: /ric/v1
    Version: 0.3.3
    License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
