// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteSubscriptionNoContentCode is the HTTP code returned for type DeleteSubscriptionNoContent
const DeleteSubscriptionNoContentCode int = 204

/*DeleteSubscriptionNoContent Successful deletion of subscription

swagger:response deleteSubscriptionNoContent
*/
type DeleteSubscriptionNoContent struct {
}

// NewDeleteSubscriptionNoContent creates DeleteSubscriptionNoContent with default headers values
func NewDeleteSubscriptionNoContent() *DeleteSubscriptionNoContent {

	return &DeleteSubscriptionNoContent{}
}

// WriteResponse to the client
func (o *DeleteSubscriptionNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteSubscriptionBadRequestCode is the HTTP code returned for type DeleteSubscriptionBadRequest
const DeleteSubscriptionBadRequestCode int = 400

/*DeleteSubscriptionBadRequest Invalid subscription supplied

swagger:response deleteSubscriptionBadRequest
*/
type DeleteSubscriptionBadRequest struct {
}

// NewDeleteSubscriptionBadRequest creates DeleteSubscriptionBadRequest with default headers values
func NewDeleteSubscriptionBadRequest() *DeleteSubscriptionBadRequest {

	return &DeleteSubscriptionBadRequest{}
}

// WriteResponse to the client
func (o *DeleteSubscriptionBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
