// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "gerrit.o-ran-sc.org/r/ric-plt/appmgr/pkg/models"
)

// NewDeregisterXappParams creates a new DeregisterXappParams object
// no default values defined in spec.
func NewDeregisterXappParams() DeregisterXappParams {

	return DeregisterXappParams{}
}

// DeregisterXappParams contains all the bound params for the deregister xapp operation
// typically these are obtained from a http.Request
//
// swagger:parameters deregisterXapp
type DeregisterXappParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Xapp to be unregistered
	  Required: true
	  In: body
	*/
	DeregisterRequest *models.DeregisterRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewDeregisterXappParams() beforehand.
func (o *DeregisterXappParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.DeregisterRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("deregisterRequest", "body"))
			} else {
				res = append(res, errors.NewParseError("deregisterRequest", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.DeregisterRequest = &body
			}
		}
	} else {
		res = append(res, errors.Required("deregisterRequest", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
