// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeregisterXappNoContentCode is the HTTP code returned for type DeregisterXappNoContent
const DeregisterXappNoContentCode int = 204

/*DeregisterXappNoContent Successful deregistration of xApp

swagger:response deregisterXappNoContent
*/
type DeregisterXappNoContent struct {
}

// NewDeregisterXappNoContent creates DeregisterXappNoContent with default headers values
func NewDeregisterXappNoContent() *DeregisterXappNoContent {

	return &DeregisterXappNoContent{}
}

// WriteResponse to the client
func (o *DeregisterXappNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeregisterXappBadRequestCode is the HTTP code returned for type DeregisterXappBadRequest
const DeregisterXappBadRequestCode int = 400

/*DeregisterXappBadRequest Invalid xApp name supplied

swagger:response deregisterXappBadRequest
*/
type DeregisterXappBadRequest struct {
}

// NewDeregisterXappBadRequest creates DeregisterXappBadRequest with default headers values
func NewDeregisterXappBadRequest() *DeregisterXappBadRequest {

	return &DeregisterXappBadRequest{}
}

// WriteResponse to the client
func (o *DeregisterXappBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeregisterXappInternalServerErrorCode is the HTTP code returned for type DeregisterXappInternalServerError
const DeregisterXappInternalServerErrorCode int = 500

/*DeregisterXappInternalServerError Internal error

swagger:response deregisterXappInternalServerError
*/
type DeregisterXappInternalServerError struct {
}

// NewDeregisterXappInternalServerError creates DeregisterXappInternalServerError with default headers values
func NewDeregisterXappInternalServerError() *DeregisterXappInternalServerError {

	return &DeregisterXappInternalServerError{}
}

// WriteResponse to the client
func (o *DeregisterXappInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
