// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "gerrit.o-ran-sc.org/r/ric-plt/appmgr/pkg/models"
)

// GetSubscriptionsOKCode is the HTTP code returned for type GetSubscriptionsOK
const GetSubscriptionsOKCode int = 200

/*GetSubscriptionsOK successful query of subscriptions

swagger:response getSubscriptionsOK
*/
type GetSubscriptionsOK struct {

	/*
	  In: Body
	*/
	Payload models.AllSubscriptions `json:"body,omitempty"`
}

// NewGetSubscriptionsOK creates GetSubscriptionsOK with default headers values
func NewGetSubscriptionsOK() *GetSubscriptionsOK {

	return &GetSubscriptionsOK{}
}

// WithPayload adds the payload to the get subscriptions o k response
func (o *GetSubscriptionsOK) WithPayload(payload models.AllSubscriptions) *GetSubscriptionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get subscriptions o k response
func (o *GetSubscriptionsOK) SetPayload(payload models.AllSubscriptions) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSubscriptionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.AllSubscriptions{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
