// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "gerrit.o-ran-sc.org/r/ric-plt/appmgr/pkg/models"
)

// GetSubscriptionByIDOKCode is the HTTP code returned for type GetSubscriptionByIDOK
const GetSubscriptionByIDOKCode int = 200

/*GetSubscriptionByIDOK successful operation

swagger:response getSubscriptionByIdOK
*/
type GetSubscriptionByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Subscription `json:"body,omitempty"`
}

// NewGetSubscriptionByIDOK creates GetSubscriptionByIDOK with default headers values
func NewGetSubscriptionByIDOK() *GetSubscriptionByIDOK {

	return &GetSubscriptionByIDOK{}
}

// WithPayload adds the payload to the get subscription by Id o k response
func (o *GetSubscriptionByIDOK) WithPayload(payload *models.Subscription) *GetSubscriptionByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get subscription by Id o k response
func (o *GetSubscriptionByIDOK) SetPayload(payload *models.Subscription) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSubscriptionByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetSubscriptionByIDBadRequestCode is the HTTP code returned for type GetSubscriptionByIDBadRequest
const GetSubscriptionByIDBadRequestCode int = 400

/*GetSubscriptionByIDBadRequest Invalid ID supplied

swagger:response getSubscriptionByIdBadRequest
*/
type GetSubscriptionByIDBadRequest struct {
}

// NewGetSubscriptionByIDBadRequest creates GetSubscriptionByIDBadRequest with default headers values
func NewGetSubscriptionByIDBadRequest() *GetSubscriptionByIDBadRequest {

	return &GetSubscriptionByIDBadRequest{}
}

// WriteResponse to the client
func (o *GetSubscriptionByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetSubscriptionByIDNotFoundCode is the HTTP code returned for type GetSubscriptionByIDNotFound
const GetSubscriptionByIDNotFoundCode int = 404

/*GetSubscriptionByIDNotFound Subscription not found

swagger:response getSubscriptionByIdNotFound
*/
type GetSubscriptionByIDNotFound struct {
}

// NewGetSubscriptionByIDNotFound creates GetSubscriptionByIDNotFound with default headers values
func NewGetSubscriptionByIDNotFound() *GetSubscriptionByIDNotFound {

	return &GetSubscriptionByIDNotFound{}
}

// WriteResponse to the client
func (o *GetSubscriptionByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
