// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ModifySubscriptionHandlerFunc turns a function with the right signature into a modify subscription handler
type ModifySubscriptionHandlerFunc func(ModifySubscriptionParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ModifySubscriptionHandlerFunc) Handle(params ModifySubscriptionParams) middleware.Responder {
	return fn(params)
}

// ModifySubscriptionHandler interface for that can handle valid modify subscription params
type ModifySubscriptionHandler interface {
	Handle(ModifySubscriptionParams) middleware.Responder
}

// NewModifySubscription creates a new http.Handler for the modify subscription operation
func NewModifySubscription(ctx *middleware.Context, handler ModifySubscriptionHandler) *ModifySubscription {
	return &ModifySubscription{Context: ctx, Handler: handler}
}

/*ModifySubscription swagger:route PUT /subscriptions/{subscriptionId} xapp subscriptions modifySubscription

Modify event subscription

*/
type ModifySubscription struct {
	Context *middleware.Context
	Handler ModifySubscriptionHandler
}

func (o *ModifySubscription) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewModifySubscriptionParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
