// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	models "gerrit.o-ran-sc.org/r/ric-plt/appmgr/pkg/models"
)

// NewModifySubscriptionParams creates a new ModifySubscriptionParams object
// no default values defined in spec.
func NewModifySubscriptionParams() ModifySubscriptionParams {

	return ModifySubscriptionParams{}
}

// ModifySubscriptionParams contains all the bound params for the modify subscription operation
// typically these are obtained from a http.Request
//
// swagger:parameters modifySubscription
type ModifySubscriptionParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*ID of subscription
	  Required: true
	  In: path
	*/
	SubscriptionID string
	/*Modified subscription
	  Required: true
	  In: body
	*/
	SubscriptionRequest *models.SubscriptionRequest
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewModifySubscriptionParams() beforehand.
func (o *ModifySubscriptionParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rSubscriptionID, rhkSubscriptionID, _ := route.Params.GetOK("subscriptionId")
	if err := o.bindSubscriptionID(rSubscriptionID, rhkSubscriptionID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.SubscriptionRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("subscriptionRequest", "body"))
			} else {
				res = append(res, errors.NewParseError("subscriptionRequest", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.SubscriptionRequest = &body
			}
		}
	} else {
		res = append(res, errors.Required("subscriptionRequest", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindSubscriptionID binds and validates parameter SubscriptionID from path.
func (o *ModifySubscriptionParams) bindSubscriptionID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.SubscriptionID = raw

	return nil
}
