// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// RegisterXappHandlerFunc turns a function with the right signature into a register xapp handler
type RegisterXappHandlerFunc func(RegisterXappParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RegisterXappHandlerFunc) Handle(params RegisterXappParams) middleware.Responder {
	return fn(params)
}

// RegisterXappHandler interface for that can handle valid register xapp params
type RegisterXappHandler interface {
	Handle(RegisterXappParams) middleware.Responder
}

// NewRegisterXapp creates a new http.Handler for the register xapp operation
func NewRegisterXapp(ctx *middleware.Context, handler RegisterXappHandler) *RegisterXapp {
	return &RegisterXapp{Context: ctx, Handler: handler}
}

/*RegisterXapp swagger:route POST /register xapp registration registerXapp

Register a new xApp

*/
type RegisterXapp struct {
	Context *middleware.Context
	Handler RegisterXappHandler
}

func (o *RegisterXapp) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRegisterXappParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
