// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// RegisterXappCreatedCode is the HTTP code returned for type RegisterXappCreated
const RegisterXappCreatedCode int = 201

/*RegisterXappCreated Registration successful

swagger:response registerXappCreated
*/
type RegisterXappCreated struct {
}

// NewRegisterXappCreated creates RegisterXappCreated with default headers values
func NewRegisterXappCreated() *RegisterXappCreated {

	return &RegisterXappCreated{}
}

// WriteResponse to the client
func (o *RegisterXappCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// RegisterXappBadRequestCode is the HTTP code returned for type RegisterXappBadRequest
const RegisterXappBadRequestCode int = 400

/*RegisterXappBadRequest Invalid input

swagger:response registerXappBadRequest
*/
type RegisterXappBadRequest struct {
}

// NewRegisterXappBadRequest creates RegisterXappBadRequest with default headers values
func NewRegisterXappBadRequest() *RegisterXappBadRequest {

	return &RegisterXappBadRequest{}
}

// WriteResponse to the client
func (o *RegisterXappBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
