// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// AllDeployableXapps all deployable xapps
// swagger:model AllDeployableXapps
type AllDeployableXapps []string

// Validate validates this all deployable xapps
func (m AllDeployableXapps) Validate(formats strfmt.Registry) error {
	return nil
}
