// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ConfigMetadata config metadata
// swagger:model ConfigMetadata
type ConfigMetadata struct {

	// Name of the namespace
	// Required: true
	Namespace *string `json:"namespace"`

	// Name of the xApp
	// Required: true
	XappName *string `json:"xappName"`
}

// Validate validates this config metadata
func (m *ConfigMetadata) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNamespace(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateXappName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConfigMetadata) validateNamespace(formats strfmt.Registry) error {

	if err := validate.Required("namespace", "body", m.Namespace); err != nil {
		return err
	}

	return nil
}

func (m *ConfigMetadata) validateXappName(formats strfmt.Registry) error {

	if err := validate.Required("xappName", "body", m.XappName); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConfigMetadata) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConfigMetadata) UnmarshalBinary(b []byte) error {
	var res ConfigMetadata
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
