// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DeregisterRequest deregister request
// swagger:model deregisterRequest
type DeregisterRequest struct {

	// app instance name
	// Required: true
	AppInstanceName *string `json:"appInstanceName"`

	// app name
	// Required: true
	AppName *string `json:"appName"`
}

// Validate validates this deregister request
func (m *DeregisterRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAppInstanceName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAppName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeregisterRequest) validateAppInstanceName(formats strfmt.Registry) error {

	if err := validate.Required("appInstanceName", "body", m.AppInstanceName); err != nil {
		return err
	}

	return nil
}

func (m *DeregisterRequest) validateAppName(formats strfmt.Registry) error {

	if err := validate.Required("appName", "body", m.AppName); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DeregisterRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeregisterRequest) UnmarshalBinary(b []byte) error {
	var res DeregisterRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
