// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SubscriptionData subscription data
// swagger:model SubscriptionData
type SubscriptionData struct {

	// event type
	// Required: true
	EventType EventType `json:"eventType"`

	// Maximum number of retries
	// Required: true
	MaxRetries *int64 `json:"maxRetries"`

	// Time in seconds to wait before next retry
	// Required: true
	RetryTimer *int64 `json:"retryTimer"`

	// target Url
	// Required: true
	TargetURL *string `json:"targetUrl"`
}

// Validate validates this subscription data
func (m *SubscriptionData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEventType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMaxRetries(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRetryTimer(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTargetURL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SubscriptionData) validateEventType(formats strfmt.Registry) error {

	if err := m.EventType.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("eventType")
		}
		return err
	}

	return nil
}

func (m *SubscriptionData) validateMaxRetries(formats strfmt.Registry) error {

	if err := validate.Required("maxRetries", "body", m.MaxRetries); err != nil {
		return err
	}

	return nil
}

func (m *SubscriptionData) validateRetryTimer(formats strfmt.Registry) error {

	if err := validate.Required("retryTimer", "body", m.RetryTimer); err != nil {
		return err
	}

	return nil
}

func (m *SubscriptionData) validateTargetURL(formats strfmt.Registry) error {

	if err := validate.Required("targetUrl", "body", m.TargetURL); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SubscriptionData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SubscriptionData) UnmarshalBinary(b []byte) error {
	var res SubscriptionData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
