// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// XappDescriptor xapp descriptor
// swagger:model XappDescriptor
type XappDescriptor struct {

	// The exact xapp helm chart version to install
	HelmVersion string `json:"helmVersion,omitempty"`

	// Name of the namespace to which xApp is deployed. Overrides the value given in Helm chart value file.
	Namespace string `json:"namespace,omitempty"`

	// JSON string of override file for 'helm install' command
	OverrideFile interface{} `json:"overrideFile,omitempty"`

	// Name of the xapp to be visible in Kubernetes
	ReleaseName string `json:"releaseName,omitempty"`

	// Name of the xApp in helm chart
	// Required: true
	XappName *string `json:"xappName"`
}

// Validate validates this xapp descriptor
func (m *XappDescriptor) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateXappName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *XappDescriptor) validateXappName(formats strfmt.Registry) error {

	if err := validate.Required("xappName", "body", m.XappName); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *XappDescriptor) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *XappDescriptor) UnmarshalBinary(b []byte) error {
	var res XappDescriptor
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
