// Code generated by go-swagger; DO NOT EDIT.

package xapp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "gerrit.o-ran-sc.org/r/ric-plt/appmgr/pkg/models"
)

// DeployXappCreatedCode is the HTTP code returned for type DeployXappCreated
const DeployXappCreatedCode int = 201

/*DeployXappCreated xApp successfully created

swagger:response deployXappCreated
*/
type DeployXappCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Xapp `json:"body,omitempty"`
}

// NewDeployXappCreated creates DeployXappCreated with default headers values
func NewDeployXappCreated() *DeployXappCreated {

	return &DeployXappCreated{}
}

// WithPayload adds the payload to the deploy xapp created response
func (o *DeployXappCreated) WithPayload(payload *models.Xapp) *DeployXappCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the deploy xapp created response
func (o *DeployXappCreated) SetPayload(payload *models.Xapp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeployXappCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeployXappBadRequestCode is the HTTP code returned for type DeployXappBadRequest
const DeployXappBadRequestCode int = 400

/*DeployXappBadRequest Invalid input

swagger:response deployXappBadRequest
*/
type DeployXappBadRequest struct {
}

// NewDeployXappBadRequest creates DeployXappBadRequest with default headers values
func NewDeployXappBadRequest() *DeployXappBadRequest {

	return &DeployXappBadRequest{}
}

// WriteResponse to the client
func (o *DeployXappBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeployXappInternalServerErrorCode is the HTTP code returned for type DeployXappInternalServerError
const DeployXappInternalServerErrorCode int = 500

/*DeployXappInternalServerError Internal error

swagger:response deployXappInternalServerError
*/
type DeployXappInternalServerError struct {
}

// NewDeployXappInternalServerError creates DeployXappInternalServerError with default headers values
func NewDeployXappInternalServerError() *DeployXappInternalServerError {

	return &DeployXappInternalServerError{}
}

// WriteResponse to the client
func (o *DeployXappInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
