// Code generated by go-swagger; DO NOT EDIT.

package xapp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "gerrit.o-ran-sc.org/r/ric-plt/appmgr/pkg/models"
)

// GetXappInstanceByNameOKCode is the HTTP code returned for type GetXappInstanceByNameOK
const GetXappInstanceByNameOKCode int = 200

/*GetXappInstanceByNameOK successful operation

swagger:response getXappInstanceByNameOK
*/
type GetXappInstanceByNameOK struct {

	/*
	  In: Body
	*/
	Payload *models.XappInstance `json:"body,omitempty"`
}

// NewGetXappInstanceByNameOK creates GetXappInstanceByNameOK with default headers values
func NewGetXappInstanceByNameOK() *GetXappInstanceByNameOK {

	return &GetXappInstanceByNameOK{}
}

// WithPayload adds the payload to the get xapp instance by name o k response
func (o *GetXappInstanceByNameOK) WithPayload(payload *models.XappInstance) *GetXappInstanceByNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get xapp instance by name o k response
func (o *GetXappInstanceByNameOK) SetPayload(payload *models.XappInstance) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetXappInstanceByNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetXappInstanceByNameBadRequestCode is the HTTP code returned for type GetXappInstanceByNameBadRequest
const GetXappInstanceByNameBadRequestCode int = 400

/*GetXappInstanceByNameBadRequest Invalid name supplied

swagger:response getXappInstanceByNameBadRequest
*/
type GetXappInstanceByNameBadRequest struct {
}

// NewGetXappInstanceByNameBadRequest creates GetXappInstanceByNameBadRequest with default headers values
func NewGetXappInstanceByNameBadRequest() *GetXappInstanceByNameBadRequest {

	return &GetXappInstanceByNameBadRequest{}
}

// WriteResponse to the client
func (o *GetXappInstanceByNameBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetXappInstanceByNameNotFoundCode is the HTTP code returned for type GetXappInstanceByNameNotFound
const GetXappInstanceByNameNotFoundCode int = 404

/*GetXappInstanceByNameNotFound Xapp not found

swagger:response getXappInstanceByNameNotFound
*/
type GetXappInstanceByNameNotFound struct {
}

// NewGetXappInstanceByNameNotFound creates GetXappInstanceByNameNotFound with default headers values
func NewGetXappInstanceByNameNotFound() *GetXappInstanceByNameNotFound {

	return &GetXappInstanceByNameNotFound{}
}

// WriteResponse to the client
func (o *GetXappInstanceByNameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetXappInstanceByNameInternalServerErrorCode is the HTTP code returned for type GetXappInstanceByNameInternalServerError
const GetXappInstanceByNameInternalServerErrorCode int = 500

/*GetXappInstanceByNameInternalServerError Internal error

swagger:response getXappInstanceByNameInternalServerError
*/
type GetXappInstanceByNameInternalServerError struct {
}

// NewGetXappInstanceByNameInternalServerError creates GetXappInstanceByNameInternalServerError with default headers values
func NewGetXappInstanceByNameInternalServerError() *GetXappInstanceByNameInternalServerError {

	return &GetXappInstanceByNameInternalServerError{}
}

// WriteResponse to the client
func (o *GetXappInstanceByNameInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
