// Code generated by go-swagger; DO NOT EDIT.

package xapp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "gerrit.o-ran-sc.org/r/ric-plt/appmgr/pkg/models"
)

// GetAllXappsOKCode is the HTTP code returned for type GetAllXappsOK
const GetAllXappsOKCode int = 200

/*GetAllXappsOK successful query of xApps

swagger:response getAllXappsOK
*/
type GetAllXappsOK struct {

	/*
	  In: Body
	*/
	Payload models.AllDeployedXapps `json:"body,omitempty"`
}

// NewGetAllXappsOK creates GetAllXappsOK with default headers values
func NewGetAllXappsOK() *GetAllXappsOK {

	return &GetAllXappsOK{}
}

// WithPayload adds the payload to the get all xapps o k response
func (o *GetAllXappsOK) WithPayload(payload models.AllDeployedXapps) *GetAllXappsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all xapps o k response
func (o *GetAllXappsOK) SetPayload(payload models.AllDeployedXapps) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllXappsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.AllDeployedXapps{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetAllXappsInternalServerErrorCode is the HTTP code returned for type GetAllXappsInternalServerError
const GetAllXappsInternalServerErrorCode int = 500

/*GetAllXappsInternalServerError Internal error

swagger:response getAllXappsInternalServerError
*/
type GetAllXappsInternalServerError struct {
}

// NewGetAllXappsInternalServerError creates GetAllXappsInternalServerError with default headers values
func NewGetAllXappsInternalServerError() *GetAllXappsInternalServerError {

	return &GetAllXappsInternalServerError{}
}

// WriteResponse to the client
func (o *GetAllXappsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
