// Code generated by go-swagger; DO NOT EDIT.

package xapp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetConfigElementParams creates a new GetConfigElementParams object
// no default values defined in spec.
func NewGetConfigElementParams() GetConfigElementParams {

	return GetConfigElementParams{}
}

// GetConfigElementParams contains all the bound params for the get config element operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetConfigElement
type GetConfigElementParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Name of configuration element
	  Required: true
	  In: path
	*/
	Element string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetConfigElementParams() beforehand.
func (o *GetConfigElementParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rElement, rhkElement, _ := route.Params.GetOK("element")
	if err := o.bindElement(rElement, rhkElement, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindElement binds and validates parameter Element from path.
func (o *GetConfigElementParams) bindElement(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.Element = raw

	return nil
}
