// Code generated by go-swagger; DO NOT EDIT.

package xapp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "gerrit.o-ran-sc.org/r/ric-plt/appmgr/pkg/models"
)

// GetAllXappConfigOKCode is the HTTP code returned for type GetAllXappConfigOK
const GetAllXappConfigOKCode int = 200

/*GetAllXappConfigOK successful query of xApp config

swagger:response getAllXappConfigOK
*/
type GetAllXappConfigOK struct {

	/*
	  In: Body
	*/
	Payload models.AllXappConfig `json:"body,omitempty"`
}

// NewGetAllXappConfigOK creates GetAllXappConfigOK with default headers values
func NewGetAllXappConfigOK() *GetAllXappConfigOK {

	return &GetAllXappConfigOK{}
}

// WithPayload adds the payload to the get all xapp config o k response
func (o *GetAllXappConfigOK) WithPayload(payload models.AllXappConfig) *GetAllXappConfigOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all xapp config o k response
func (o *GetAllXappConfigOK) SetPayload(payload models.AllXappConfig) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllXappConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.AllXappConfig{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetAllXappConfigInternalServerErrorCode is the HTTP code returned for type GetAllXappConfigInternalServerError
const GetAllXappConfigInternalServerErrorCode int = 500

/*GetAllXappConfigInternalServerError Internal error

swagger:response getAllXappConfigInternalServerError
*/
type GetAllXappConfigInternalServerError struct {
}

// NewGetAllXappConfigInternalServerError creates GetAllXappConfigInternalServerError with default headers values
func NewGetAllXappConfigInternalServerError() *GetAllXappConfigInternalServerError {

	return &GetAllXappConfigInternalServerError{}
}

// WriteResponse to the client
func (o *GetAllXappConfigInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
