// Code generated by go-swagger; DO NOT EDIT.

package xapp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetConfigElementHandlerFunc turns a function with the right signature into a get config element handler
type GetConfigElementHandlerFunc func(GetConfigElementParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetConfigElementHandlerFunc) Handle(params GetConfigElementParams) middleware.Responder {
	return fn(params)
}

// GetConfigElementHandler interface for that can handle valid get config element params
type GetConfigElementHandler interface {
	Handle(GetConfigElementParams) middleware.Responder
}

// NewGetConfigElement creates a new http.Handler for the get config element operation
func NewGetConfigElement(ctx *middleware.Context, handler GetConfigElementHandler) *GetConfigElement {
	return &GetConfigElement{Context: ctx, Handler: handler}
}

/*GetConfigElement swagger:route GET /config/{element} xapp getConfigElement

Returns the given element of the configuration

*/
type GetConfigElement struct {
	Context *middleware.Context
	Handler GetConfigElementHandler
}

func (o *GetConfigElement) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetConfigElementParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
