// Code generated by go-swagger; DO NOT EDIT.

package xapp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetXappByNameHandlerFunc turns a function with the right signature into a get xapp by name handler
type GetXappByNameHandlerFunc func(GetXappByNameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetXappByNameHandlerFunc) Handle(params GetXappByNameParams) middleware.Responder {
	return fn(params)
}

// GetXappByNameHandler interface for that can handle valid get xapp by name params
type GetXappByNameHandler interface {
	Handle(GetXappByNameParams) middleware.Responder
}

// NewGetXappByName creates a new http.Handler for the get xapp by name operation
func NewGetXappByName(ctx *middleware.Context, handler GetXappByNameHandler) *GetXappByName {
	return &GetXappByName{Context: ctx, Handler: handler}
}

/*GetXappByName swagger:route GET /xapps/{xAppName} xapp getXappByName

Returns the status of a given xapp

*/
type GetXappByName struct {
	Context *middleware.Context
	Handler GetXappByNameHandler
}

func (o *GetXappByName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetXappByNameParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
