// Code generated by go-swagger; DO NOT EDIT.

package xapp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "gerrit.o-ran-sc.org/r/ric-plt/appmgr/pkg/models"
)

// GetConfigElementOKCode is the HTTP code returned for type GetConfigElementOK
const GetConfigElementOKCode int = 200

/*GetConfigElementOK successful query of config elements

swagger:response getConfigElementOK
*/
type GetConfigElementOK struct {

	/*
	  In: Body
	*/
	Payload models.AllXappConfig `json:"body,omitempty"`
}

// NewGetConfigElementOK creates GetConfigElementOK with default headers values
func NewGetConfigElementOK() *GetConfigElementOK {

	return &GetConfigElementOK{}
}

// WithPayload adds the payload to the get config element o k response
func (o *GetConfigElementOK) WithPayload(payload models.AllXappConfig) *GetConfigElementOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config element o k response
func (o *GetConfigElementOK) SetPayload(payload models.AllXappConfig) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigElementOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.AllXappConfig{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetConfigElementInternalServerErrorCode is the HTTP code returned for type GetConfigElementInternalServerError
const GetConfigElementInternalServerErrorCode int = 500

/*GetConfigElementInternalServerError Internal error

swagger:response getConfigElementInternalServerError
*/
type GetConfigElementInternalServerError struct {
}

// NewGetConfigElementInternalServerError creates GetConfigElementInternalServerError with default headers values
func NewGetConfigElementInternalServerError() *GetConfigElementInternalServerError {

	return &GetConfigElementInternalServerError{}
}

// WriteResponse to the client
func (o *GetConfigElementInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
