// Code generated by go-swagger; DO NOT EDIT.

package xapp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "gerrit.o-ran-sc.org/r/ric-plt/appmgr/pkg/models"
)

// GetXappByNameOKCode is the HTTP code returned for type GetXappByNameOK
const GetXappByNameOKCode int = 200

/*GetXappByNameOK successful operation

swagger:response getXappByNameOK
*/
type GetXappByNameOK struct {

	/*
	  In: Body
	*/
	Payload *models.Xapp `json:"body,omitempty"`
}

// NewGetXappByNameOK creates GetXappByNameOK with default headers values
func NewGetXappByNameOK() *GetXappByNameOK {

	return &GetXappByNameOK{}
}

// WithPayload adds the payload to the get xapp by name o k response
func (o *GetXappByNameOK) WithPayload(payload *models.Xapp) *GetXappByNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get xapp by name o k response
func (o *GetXappByNameOK) SetPayload(payload *models.Xapp) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetXappByNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetXappByNameBadRequestCode is the HTTP code returned for type GetXappByNameBadRequest
const GetXappByNameBadRequestCode int = 400

/*GetXappByNameBadRequest Invalid ID supplied

swagger:response getXappByNameBadRequest
*/
type GetXappByNameBadRequest struct {
}

// NewGetXappByNameBadRequest creates GetXappByNameBadRequest with default headers values
func NewGetXappByNameBadRequest() *GetXappByNameBadRequest {

	return &GetXappByNameBadRequest{}
}

// WriteResponse to the client
func (o *GetXappByNameBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetXappByNameNotFoundCode is the HTTP code returned for type GetXappByNameNotFound
const GetXappByNameNotFoundCode int = 404

/*GetXappByNameNotFound Xapp not found

swagger:response getXappByNameNotFound
*/
type GetXappByNameNotFound struct {
}

// NewGetXappByNameNotFound creates GetXappByNameNotFound with default headers values
func NewGetXappByNameNotFound() *GetXappByNameNotFound {

	return &GetXappByNameNotFound{}
}

// WriteResponse to the client
func (o *GetXappByNameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetXappByNameInternalServerErrorCode is the HTTP code returned for type GetXappByNameInternalServerError
const GetXappByNameInternalServerErrorCode int = 500

/*GetXappByNameInternalServerError Internal error

swagger:response getXappByNameInternalServerError
*/
type GetXappByNameInternalServerError struct {
}

// NewGetXappByNameInternalServerError creates GetXappByNameInternalServerError with default headers values
func NewGetXappByNameInternalServerError() *GetXappByNameInternalServerError {

	return &GetXappByNameInternalServerError{}
}

// WriteResponse to the client
func (o *GetXappByNameInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
