// Code generated by go-swagger; DO NOT EDIT.

package xapp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAllXappsHandlerFunc turns a function with the right signature into a get all xapps handler
type GetAllXappsHandlerFunc func(GetAllXappsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllXappsHandlerFunc) Handle(params GetAllXappsParams) middleware.Responder {
	return fn(params)
}

// GetAllXappsHandler interface for that can handle valid get all xapps params
type GetAllXappsHandler interface {
	Handle(GetAllXappsParams) middleware.Responder
}

// NewGetAllXapps creates a new http.Handler for the get all xapps operation
func NewGetAllXapps(ctx *middleware.Context, handler GetAllXappsHandler) *GetAllXapps {
	return &GetAllXapps{Context: ctx, Handler: handler}
}

/*GetAllXapps swagger:route GET /xapps xapp getAllXapps

Returns the status of all xapps

*/
type GetAllXapps struct {
	Context *middleware.Context
	Handler GetAllXappsHandler
}

func (o *GetAllXapps) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAllXappsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
