// Code generated by go-swagger; DO NOT EDIT.

package xapp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "gerrit.o-ran-sc.org/r/ric-plt/appmgr/pkg/models"
)

// ListAllXappsOKCode is the HTTP code returned for type ListAllXappsOK
const ListAllXappsOKCode int = 200

/*ListAllXappsOK successful list of deployable xApps

swagger:response listAllXappsOK
*/
type ListAllXappsOK struct {

	/*
	  In: Body
	*/
	Payload models.AllDeployableXapps `json:"body,omitempty"`
}

// NewListAllXappsOK creates ListAllXappsOK with default headers values
func NewListAllXappsOK() *ListAllXappsOK {

	return &ListAllXappsOK{}
}

// WithPayload adds the payload to the list all xapps o k response
func (o *ListAllXappsOK) WithPayload(payload models.AllDeployableXapps) *ListAllXappsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list all xapps o k response
func (o *ListAllXappsOK) SetPayload(payload models.AllDeployableXapps) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListAllXappsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.AllDeployableXapps{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListAllXappsInternalServerErrorCode is the HTTP code returned for type ListAllXappsInternalServerError
const ListAllXappsInternalServerErrorCode int = 500

/*ListAllXappsInternalServerError Internal error

swagger:response listAllXappsInternalServerError
*/
type ListAllXappsInternalServerError struct {
}

// NewListAllXappsInternalServerError creates ListAllXappsInternalServerError with default headers values
func NewListAllXappsInternalServerError() *ListAllXappsInternalServerError {

	return &ListAllXappsInternalServerError{}
}

// WriteResponse to the client
func (o *ListAllXappsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
