// Code generated by go-swagger; DO NOT EDIT.

package xapp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ListAllXappsHandlerFunc turns a function with the right signature into a list all xapps handler
type ListAllXappsHandlerFunc func(ListAllXappsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListAllXappsHandlerFunc) Handle(params ListAllXappsParams) middleware.Responder {
	return fn(params)
}

// ListAllXappsHandler interface for that can handle valid list all xapps params
type ListAllXappsHandler interface {
	Handle(ListAllXappsParams) middleware.Responder
}

// NewListAllXapps creates a new http.Handler for the list all xapps operation
func NewListAllXapps(ctx *middleware.Context, handler ListAllXappsHandler) *ListAllXapps {
	return &ListAllXapps{Context: ctx, Handler: handler}
}

/*ListAllXapps swagger:route GET /xapps/list xapp listAllXapps

Returns the list of all deployable xapps

*/
type ListAllXapps struct {
	Context *middleware.Context
	Handler ListAllXappsHandler
}

func (o *ListAllXapps) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewListAllXappsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
