// Code generated by go-swagger; DO NOT EDIT.

package xapp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "gerrit.o-ran-sc.org/r/ric-plt/appmgr/pkg/models"
)

// ModifyXappConfigOKCode is the HTTP code returned for type ModifyXappConfigOK
const ModifyXappConfigOKCode int = 200

/*ModifyXappConfigOK xApp config successfully modified

swagger:response modifyXappConfigOK
*/
type ModifyXappConfigOK struct {

	/*
	  In: Body
	*/
	Payload models.ConfigValidationErrors `json:"body,omitempty"`
}

// NewModifyXappConfigOK creates ModifyXappConfigOK with default headers values
func NewModifyXappConfigOK() *ModifyXappConfigOK {

	return &ModifyXappConfigOK{}
}

// WithPayload adds the payload to the modify xapp config o k response
func (o *ModifyXappConfigOK) WithPayload(payload models.ConfigValidationErrors) *ModifyXappConfigOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the modify xapp config o k response
func (o *ModifyXappConfigOK) SetPayload(payload models.ConfigValidationErrors) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ModifyXappConfigOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.ConfigValidationErrors{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ModifyXappConfigBadRequestCode is the HTTP code returned for type ModifyXappConfigBadRequest
const ModifyXappConfigBadRequestCode int = 400

/*ModifyXappConfigBadRequest Invalid input

swagger:response modifyXappConfigBadRequest
*/
type ModifyXappConfigBadRequest struct {
}

// NewModifyXappConfigBadRequest creates ModifyXappConfigBadRequest with default headers values
func NewModifyXappConfigBadRequest() *ModifyXappConfigBadRequest {

	return &ModifyXappConfigBadRequest{}
}

// WriteResponse to the client
func (o *ModifyXappConfigBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// ModifyXappConfigUnprocessableEntityCode is the HTTP code returned for type ModifyXappConfigUnprocessableEntity
const ModifyXappConfigUnprocessableEntityCode int = 422

/*ModifyXappConfigUnprocessableEntity Validation of configuration failed

swagger:response modifyXappConfigUnprocessableEntity
*/
type ModifyXappConfigUnprocessableEntity struct {
}

// NewModifyXappConfigUnprocessableEntity creates ModifyXappConfigUnprocessableEntity with default headers values
func NewModifyXappConfigUnprocessableEntity() *ModifyXappConfigUnprocessableEntity {

	return &ModifyXappConfigUnprocessableEntity{}
}

// WriteResponse to the client
func (o *ModifyXappConfigUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(422)
}

// ModifyXappConfigInternalServerErrorCode is the HTTP code returned for type ModifyXappConfigInternalServerError
const ModifyXappConfigInternalServerErrorCode int = 500

/*ModifyXappConfigInternalServerError Internal error

swagger:response modifyXappConfigInternalServerError
*/
type ModifyXappConfigInternalServerError struct {
}

// NewModifyXappConfigInternalServerError creates ModifyXappConfigInternalServerError with default headers values
func NewModifyXappConfigInternalServerError() *ModifyXappConfigInternalServerError {

	return &ModifyXappConfigInternalServerError{}
}

// WriteResponse to the client
func (o *ModifyXappConfigInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
