// Code generated by go-swagger; DO NOT EDIT.

package xapp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// UndeployXappNoContentCode is the HTTP code returned for type UndeployXappNoContent
const UndeployXappNoContentCode int = 204

/*UndeployXappNoContent Successful deletion of xApp

swagger:response undeployXappNoContent
*/
type UndeployXappNoContent struct {
}

// NewUndeployXappNoContent creates UndeployXappNoContent with default headers values
func NewUndeployXappNoContent() *UndeployXappNoContent {

	return &UndeployXappNoContent{}
}

// WriteResponse to the client
func (o *UndeployXappNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// UndeployXappBadRequestCode is the HTTP code returned for type UndeployXappBadRequest
const UndeployXappBadRequestCode int = 400

/*UndeployXappBadRequest Invalid xApp name supplied

swagger:response undeployXappBadRequest
*/
type UndeployXappBadRequest struct {
}

// NewUndeployXappBadRequest creates UndeployXappBadRequest with default headers values
func NewUndeployXappBadRequest() *UndeployXappBadRequest {

	return &UndeployXappBadRequest{}
}

// WriteResponse to the client
func (o *UndeployXappBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UndeployXappInternalServerErrorCode is the HTTP code returned for type UndeployXappInternalServerError
const UndeployXappInternalServerErrorCode int = 500

/*UndeployXappInternalServerError Internal error

swagger:response undeployXappInternalServerError
*/
type UndeployXappInternalServerError struct {
}

// NewUndeployXappInternalServerError creates UndeployXappInternalServerError with default headers values
func NewUndeployXappInternalServerError() *UndeployXappInternalServerError {

	return &UndeployXappInternalServerError{}
}

// WriteResponse to the client
func (o *UndeployXappInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
